# Generated by Django 4.2.3 on 2023-07-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
