# Generated by Django 4.2.3 on 2023-07-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsite', '0003_customer_order_alter_products_image_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
