# Generated by Django 4.2.4 on 2023-08-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsite', '0004_shippingaddress_firstname_shippingaddress_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bool', models.BooleanField(default='False')),
                ('stripe_checkout_id', models.CharField(max_length=500)),
            ],
        ),
    ]
